// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJsSU9auiHKkvg4ymJFa6ZB6SKd4Zf1_o',
    appId: '1:845147280306:web:963ebff8dd6af899f28aab',
    messagingSenderId: '845147280306',
    projectId: 'fir-live-score-89586',
    authDomain: 'fir-live-score-89586.firebaseapp.com',
    storageBucket: 'fir-live-score-89586.firebasestorage.app',
    measurementId: 'G-ZYWQ0S1FHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFVYi2EomROvcnLhLM4cECJ9vtYMQUMr8',
    appId: '1:845147280306:android:53e182cd46d5a4cdf28aab',
    messagingSenderId: '845147280306',
    projectId: 'fir-live-score-89586',
    storageBucket: 'fir-live-score-89586.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBpZeUOp-8bMXJwQ4esQ_i_aM37APGGY8',
    appId: '1:845147280306:ios:c9807bbfd79b2b5df28aab',
    messagingSenderId: '845147280306',
    projectId: 'fir-live-score-89586',
    storageBucket: 'fir-live-score-89586.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLiveScore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBpZeUOp-8bMXJwQ4esQ_i_aM37APGGY8',
    appId: '1:845147280306:ios:c9807bbfd79b2b5df28aab',
    messagingSenderId: '845147280306',
    projectId: 'fir-live-score-89586',
    storageBucket: 'fir-live-score-89586.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLiveScore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJsSU9auiHKkvg4ymJFa6ZB6SKd4Zf1_o',
    appId: '1:845147280306:web:5ce60295b697f5b1f28aab',
    messagingSenderId: '845147280306',
    projectId: 'fir-live-score-89586',
    authDomain: 'fir-live-score-89586.firebaseapp.com',
    storageBucket: 'fir-live-score-89586.firebasestorage.app',
    measurementId: 'G-16GN4P0921',
  );
}
